### ISSUE TITLE
Post: blogging from iOS with GitHub mobile and actions

### ISSUE THREAD

**Issue by TownLake** [TownLake/blog-samrhea-legacy#2]

**Comment by vences** [comment]
Hi Sam, 

Just an idea on that:
App to consider when you are blogging on your iOS is Working Copy (pro version for pushing change):
- Git repo with offline editing
- shortcut integration with callback: https://workingcopyapp.com/url-schemes.html#x-callback-url

Never tested Github mobile, just bringing another app
